// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKXe40_bAN1FgzI3fGLZMj1sDMuTEijM',
    appId: '1:239864358715:web:2b8e26c9d5914920bd791e',
    messagingSenderId: '239864358715',
    projectId: 'todo-reminder-e2ddb',
    authDomain: 'todo-reminder-e2ddb.firebaseapp.com',
    storageBucket: 'todo-reminder-e2ddb.appspot.com',
    measurementId: 'G-ZG15R7XB5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiRhJhK-rj39P8rZInaw2F41z45R80g0',
    appId: '1:239864358715:android:7d2d3f78c2565a34bd791e',
    messagingSenderId: '239864358715',
    projectId: 'todo-reminder-e2ddb',
    storageBucket: 'todo-reminder-e2ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqk776uILHlX6yhejG3UeHrmVsq6oL-Wg',
    appId: '1:239864358715:ios:d8db23d56d5a82e0bd791e',
    messagingSenderId: '239864358715',
    projectId: 'todo-reminder-e2ddb',
    storageBucket: 'todo-reminder-e2ddb.appspot.com',
    androidClientId: '239864358715-ece5dp1i7b9iqelnb5maqbq0f6mnu26i.apps.googleusercontent.com',
    iosClientId: '239864358715-77dr7ahtk7dmosvl876ltiiu03j08f1c.apps.googleusercontent.com',
    iosBundleId: 'com.deslopers.todolist',
  );
}
