/// Flutter icons MNCustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MNCustomIcons
///      fonts:
///       - asset: fonts/MNCustomIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MNCustomIcons {
  MNCustomIcons._();

  static const _kFontFam = 'MNCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData google_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData icons8_google_48 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
